/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrentDualMatchDetailsDto } from '../../models/current-dual-match-details-dto';

export interface ConfirmCurrentDualMatchCancellation$Params {
  confirmed: boolean;
}

export function confirmCurrentDualMatchCancellation(http: HttpClient, rootUrl: string, params: ConfirmCurrentDualMatchCancellation$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentDualMatchDetailsDto>> {
  const rb = new RequestBuilder(rootUrl, confirmCurrentDualMatchCancellation.PATH, 'put');
  if (params) {
    rb.query('confirmed', params.confirmed, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CurrentDualMatchDetailsDto>;
    })
  );
}

confirmCurrentDualMatchCancellation.PATH = '/matches/me/current-dual-match/cancel-confirmation';
