/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrentDualMatchDetailsDto } from '../../models/current-dual-match-details-dto';

export interface FindMyCurrentDualMatchDetails$Params {
}

export function findMyCurrentDualMatchDetails(http: HttpClient, rootUrl: string, params?: FindMyCurrentDualMatchDetails$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentDualMatchDetailsDto>> {
  const rb = new RequestBuilder(rootUrl, findMyCurrentDualMatchDetails.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CurrentDualMatchDetailsDto>;
    })
  );
}

findMyCurrentDualMatchDetails.PATH = '/matches/me/current-dual-match';
