/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Register$Params } from './fn/authentication-controller/register';
export { register } from './fn/authentication-controller/register';
export type { Login$Params } from './fn/authentication-controller/login';
export { login } from './fn/authentication-controller/login';
export type { ConfirmToken$Params } from './fn/authentication-controller/confirm-token';
export { confirmToken } from './fn/authentication-controller/confirm-token';
