/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TeamDto } from '../../models/team-dto';

export interface FindCompleteTeamsInMyCity$Params {
}

export function findCompleteTeamsInMyCity(http: HttpClient, rootUrl: string, params?: FindCompleteTeamsInMyCity$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TeamDto>>> {
  const rb = new RequestBuilder(rootUrl, findCompleteTeamsInMyCity.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TeamDto>>;
    })
  );
}

findCompleteTeamsInMyCity.PATH = '/teams/me/complete-in-my-city';
