/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvailablePlayerDto } from '../../models/available-player-dto';

export interface FindAvailablePlayersInMyLocation$Params {
}

export function findAvailablePlayersInMyLocation(http: HttpClient, rootUrl: string, params?: FindAvailablePlayersInMyLocation$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AvailablePlayerDto>>> {
  const rb = new RequestBuilder(rootUrl, findAvailablePlayersInMyLocation.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AvailablePlayerDto>>;
    })
  );
}

findAvailablePlayersInMyLocation.PATH = '/users/available/local';
