/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenValidationResponse } from '../../models/token-validation-response';

export interface ValidatePasswordResetToken$Params {
  token: string;
}

export function validatePasswordResetToken(http: HttpClient, rootUrl: string, params: ValidatePasswordResetToken$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenValidationResponse>> {
  const rb = new RequestBuilder(rootUrl, validatePasswordResetToken.PATH, 'get');
  if (params) {
    rb.query('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenValidationResponse>;
    })
  );
}

validatePasswordResetToken.PATH = '/auth/password-reset/validate';
