/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateTeamInvitationRequest } from '../../models/create-team-invitation-request';
import { TeamInvitationDto } from '../../models/team-invitation-dto';

export interface CreateInvitationMatch$Params {
      body: CreateTeamInvitationRequest
}

export function createInvitationMatch(http: HttpClient, rootUrl: string, params: CreateInvitationMatch$Params, context?: HttpContext): Observable<StrictHttpResponse<TeamInvitationDto>> {
  const rb = new RequestBuilder(rootUrl, createInvitationMatch.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TeamInvitationDto>;
    })
  );
}

createInvitationMatch.PATH = '/team-invitations/match';
