/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TeamInvitationDto } from '../../models/team-invitation-dto';

export interface FindMemberInvitations$Params {
}

export function findMemberInvitations(http: HttpClient, rootUrl: string, params?: FindMemberInvitations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TeamInvitationDto>>> {
  const rb = new RequestBuilder(rootUrl, findMemberInvitations.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TeamInvitationDto>>;
    })
  );
}

findMemberInvitations.PATH = '/team-invitations/memberInvite';
