/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TeamInvitationDto } from '../../models/team-invitation-dto';

export interface RejectInvitation$Params {
  id: number;
}

export function rejectInvitation(http: HttpClient, rootUrl: string, params: RejectInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<TeamInvitationDto>> {
  const rb = new RequestBuilder(rootUrl, rejectInvitation.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TeamInvitationDto>;
    })
  );
}

rejectInvitation.PATH = '/team-invitations/{id}/rejet';
