/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTeamInvitationRequest {
  availableDate?: string;
  endTime?: string;
  invitedUserId?: number;
  startTime?: string;
}
