/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TeamDto } from '../models/team-dto';
export interface CurrentDualMatchDetailsDto {
  location?: string;
  matchDate?: string;
  matchId?: number;
  myTeam?: TeamDto;
  opponentTeam?: TeamDto;
  startTime?: string;
}
