/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CurrentMatchDto {
  location?: string;
  matchDate?: string;
  matchId?: number;
  myTeamId?: number;
  myTeamName?: string;
  opponentTeamId?: number;
  opponentTeamName?: string;
  startTime?: string;
}
