/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DisponibilityDetailDto {
  availableDate?: string;
  endTime?: string;
  id?: number;
  startTime?: string;
  userId?: number;
}
