/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FinishMatchPlayerResultDto } from '../models/finish-match-player-result-dto';
export interface FinishCurrentDualMatchRequest {
  myTeamId?: number;
  myTeamScore?: number;
  opponentTeamId?: number;
  opponentTeamScore?: number;
  players?: Array<FinishMatchPlayerResultDto>;
}
