/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamInvitationDto {
  availableDate?: string;
  createdDate?: string;
  endTime?: string;
  id?: number;
  invitedUserFirstName?: string;
  invitedUserId?: number;
  invitedUserLastName?: string;
  startTime?: string;
  status?: 'EN_ATTENTE' | 'ACCEPTEE' | 'REFUSEE';
  teamId?: number;
  teamName?: string;
}
