/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TeamMemberDto } from '../models/team-member-dto';
export interface TeamDto {
  availableDate?: string;
  captainId?: number;
  city?: string;
  country?: string;
  createdDate?: string;
  endTime?: string;
  id?: number;
  logoUrl?: string;
  matchesDrawn?: number;
  matchesLost?: number;
  matchesWon?: number;
  members?: Array<TeamMemberDto>;
  name?: string;
  pitchAddress?: string;
  prix?: number;
  startTime?: string;
  status?: 'INACTIVE' | 'INCOMPLETE' | 'COMPLETE' | 'IN_MATCH';
  tarificationTerrain?: 'GRATUIT' | 'PAYANT';
  teamLevel?: 'DEBUTANT' | 'AVANCE' | 'AMATEUR';
  formation?: string;
  titleAddress?: string;
  totalMatches?: number;
}
