/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamInvitationDto {
  availableDate?: string;
  endTime?: string;
  id?: number;
  invitedUserFirstName?: string;
  invitedUserId?: number;
  invitedUserLastName?: string;
  invitedUserLevel?: string;
  receiverTeamId?: number;
  receiverTeamName?: string;
  senderTeamId?: number;
  senderTeamName?: string;
  startTime?: string;
  status?: 'EN_ATTENTE' | 'ACCEPTEE' | 'REFUSEE' | 'ANNULLEE';
  type?: 'PLAYER' | 'MATCH';
}
