/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TeamMemberDto } from '../models/team-member-dto';
export interface TeamDto {
  captainId?: number;
  city?: string;
  country?: string;
  createdDate?: string;
  id?: number;
  logoUrl?: string;
  members?: Array<TeamMemberDto>;
  name?: string;
  status?: 'INCOMPLETE' | 'COMPLETE' | 'IN_MATCH';
}
