/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamMemberDto {
  captain?: boolean;
  firstName?: string;
  id?: number;
  jerseyNumber?: number;
  lastName?: string;
  level?: string;
  position?: 'GOALKEEPER' | 'DEFENDER' | 'MIDFIELDER' | 'ATTACKER';
  selection?: 'STARTER' | 'SUBSTITUTE';
  teamId?: number;
  totalMatches?: number;
  userId?: number;
}
