/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  active?: boolean;
  availabilityStatus?: 'INDISPONIBLE' | 'DISPONIBLE' | 'EN_EQUIPE';
  city: string;
  confirmPassword: string;
  country: string;
  email: string;
  firstName: string;
  id?: number;
  lastName: string;
  password: string;
  username: string;
}
